/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "primary-fixed-dim": "#b5c4ff",
        "on-primary-fixed-variant": "#153ea3",
        "outline": "#747684",
        "primary": "#002068",
        "inverse-on-surface": "#eff1f3",
        "tertiary": "#1b2931",
        "surface-bright": "#f7f9fb",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#001e30",
        "background": "#f7f9fb",
        "primary-container": "#003399",
        "surface-container": "#eceef0",
        "on-primary": "#ffffff",
        "surface-tint": "#3557bc",
        "outline-variant": "#c4c5d5",
        "secondary-fixed-dim": "#93cdfc",
        "secondary-container": "#95cfff",
        "on-primary-container": "#8aa4ff",
        "secondary": "#21638d",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "on-secondary-container": "#105982",
        "on-surface": "#191c1e",
        "on-tertiary-fixed": "#0f1d25",
        "error": "#ba1a1a",
        "surface-variant": "#e0e3e5",
        "surface": "#f7f9fb",
        "on-tertiary-fixed-variant": "#3b4951",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#9baab4",
        "on-error-container": "#93000a",
        "secondary-fixed": "#cbe6ff",
        "on-background": "#191c1e",
        "tertiary-fixed-dim": "#bac9d3",
        "on-surface-variant": "#444653",
        "primary-fixed": "#dce1ff",
        "tertiary-container": "#313f47",
        "surface-container-highest": "#e0e3e5",
        "tertiary-fixed": "#d6e5ef",
        "on-primary-fixed": "#00164e",
        "inverse-surface": "#2d3133",
        "on-secondary-fixed-variant": "#004b71",
        "surface-container-high": "#e6e8ea",
        "surface-dim": "#d8dadc",
        "inverse-primary": "#b5c4ff",
        "error-container": "#ffdad6"
      },
      "borderRadius": {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      "spacing": {
        "gutter": "24px",
        "sidebar-width": "280px",
        "card-gap": "20px",
        "unit": "8px",
        "container-padding": "32px"
      },
      "fontFamily": {
        "headline-md": ["Inter"],
        "headline-lg": ["Inter"],
        "label-sm": ["Inter"],
        "body-md": ["Inter"],
        "label-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "body-lg": ["Inter"],
        "display-lg": ["Inter"]
      },
      "fontSize": {
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}]
      }
    }
  },
  plugins: [],
}
